"""Backend contract for Stage 4 Windows system capabilities."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from wyzer.models import (
    MonitorDestination,
    MonitorInfo,
    ProcessInfo,
    WindowInfo,
    WindowMoveOutcome,
)


class WindowsSystemBackend(Protocol):
    def system_profile(self) -> dict[str, Any]: ...

    def diagnose_system(self, *, scope: str = "auto") -> dict[str, Any]: ...

    def search_applications(self, query: str) -> list[dict[str, str]]: ...

    def list_installed_applications(self) -> list[dict[str, str]]: ...

    def list_installed_games(self) -> list[dict[str, str]]: ...

    def refresh_application_index(self) -> int: ...

    def list_processes(self) -> list[ProcessInfo]: ...

    def is_process_running(
        self, *, process_id: int | None = None, name: str | None = None
    ) -> bool: ...

    def launch_application(self, application: str) -> tuple[int | None, str]: ...

    def open_file(self, path: Path) -> None: ...

    def control_media(self, action: str) -> None: ...

    def current_media(self) -> dict[str, str | bool | None]: ...

    def control_volume(self, action: str) -> None: ...

    def control_master_audio(
        self, operation: str, amount: int | None = None, level: int | None = None
    ) -> dict[str, Any]: ...

    def list_audio_sessions(self) -> dict[str, Any]: ...

    def control_application_audio(
        self,
        application: str,
        operation: str,
        amount: int | None = None,
        level: int | None = None,
        scope: str = "all",
    ) -> dict[str, Any]: ...

    def mute_audio_sessions_except(self, applications: list[str]) -> dict[str, Any]: ...

    def audio_diagnostic(self) -> dict[str, Any]: ...

    def list_windows(self) -> list[WindowInfo]: ...

    def find_windows(self, query: str) -> list[WindowInfo]: ...

    def foreground_window(self) -> WindowInfo | None: ...

    def focus_window(self, handle: int) -> bool: ...

    def minimize_window(self, handle: int) -> bool: ...

    def maximize_window(self, handle: int) -> bool: ...

    def restore_window(self, handle: int) -> bool: ...

    def close_window(self, handle: int, timeout_seconds: float = 3) -> bool: ...

    def move_window_to_monitor(
        self, handle: int, destination: MonitorDestination
    ) -> WindowMoveOutcome: ...

    def list_monitors(self) -> list[MonitorInfo]: ...
